services:
  - type: web
    name: api-prediccion-frenos
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
